[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/img/*"
  to = "/.netlify/functions/serve?img=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/download/*"
  to = "/.netlify/functions/watermark?img=:splat"
  status = 200
  force = true
